version: "3.9"

services:
  controller:
    build: ./docker/controller
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=eu-central-1

  ui:
    build: ./ui
    ports:
      - "5173:5173"
